# .github/workflows/git-sync.yml

name: ESaaS2-2022-Group5
on:
  push:
    branches:
      - main
  schedule:
  - cron:  "* * * * *"

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        env:
          CS_GITHUB_TOKEN : ${{ secrets.CS_GITHUB_TOKEN }}
          GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN }}
        uses: wei/git-sync@v3
        with:
          source_repo: "https://AkideLiu:$CS_GITHUB_TOKEN@github.cs.adelaide.edu.au/a1781032/ESaaS2-2022-Group5.git"
          source_branch: "refs/heads/*"
          destination_repo: "https://AkideLiu:$GITLAB_TOKEN@gitlab.dev.vmv.re/essi/ESaaS2-2022-Group5.git"
          destination_branch: "refs/heads/*"

