# .github/workflows/git-sync.yml

name: ESaaS2-2022-Group5
on:
  push:
    branches:
      - main
  schedule:
  - cron:  "*/5 * * * *"

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.cs.adelaide.edu.au:a1781032/ESaaS2-2022-Group5.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "https://AkideLiu:$GITLAB_TOKEN@gitlab.dev.vmv.re/essi/ESaaS2-2022-Group5.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`